name: eShop deploy

on:
  push:
    paths:
    - 'deploy/k8s/helm-simple/coupon/*'
    branches: [ main ]

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1.4.5
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v2
      with:
        resource-group: 'eshop-learn-rg'
        cluster-name: 'eshop-learn-aks'

    - name: Get code from the repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Helm tool installer
      uses: Azure/setup-helm@v3.5

    - name: Deploy
      run: >
        helm upgrade 
        eshoplearn-coupon './deploy/k8s/helm-simple/coupon'
        --install
        --namespace=default 
        --set registry=${{ secrets.REGISTRY_LOGIN_SERVER }} 
        --set imagePullPolicy=Always 
        --set host=${{ secrets.IP_ADDRESS }} 
        --set protocol=http
